version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27022:27017"
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-node-api
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    restart: always
    ports:
      - "5055:5055"
      - "9222:9222"
    links:
      - mongo
